# Generated by Django 6.0.1 on 2026-02-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricealert',
            name='depart_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='seat_class',
            field=models.CharField(default='economy', max_length=30),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='threshold_percent',
            field=models.IntegerField(default=15),
        ),
    ]
