# Generated by Django 6.0.1 on 2026-02-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_category_alter_notification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='depart_date',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='destination',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='origin',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='seat_class',
            field=models.CharField(blank=True, default='economy', max_length=30),
        ),
    ]
