# Generated by Django 6.0.1 on 2026-03-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_depart_date_notification_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='destination',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='origin',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='destination',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='origin',
            field=models.CharField(max_length=20),
        ),
    ]
