# Generated by Django 6.0.1 on 2026-02-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'CONFIRMED'), ('pending', 'PENDING'), ('cancelled', 'CANCELLED')], default='confirmed', max_length=20),
        ),
    ]
