# Generated by Django 6.0.1 on 2026-02-17 14:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_seat_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_ref_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='not_applicable', max_length=20),
        ),
    ]
