# Generated by Django 6.0.1 on 2026-02-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
