# Generated by Django 6.0.1 on 2026-02-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_flight_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_no',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='source',
            field=models.CharField(max_length=100),
        ),
    ]
