# Generated by Django 6.0.1 on 2026-02-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_flight_airline_alter_flight_arrival_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='arrival_time',
        ),
        migrations.AddField(
            model_name='flight',
            name='distance_km',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
