# Generated by Django 6.0.1 on 2026-02-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_remove_flight_arrival_time_flight_distance_km_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='distance_km',
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_time',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='destination_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='flight',
            name='source_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='flight',
            name='seats',
            field=models.IntegerField(default=180),
        ),
    ]
