# Generated by Django 6.0.1 on 2026-02-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_remove_flight_distance_km_flight_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='business_fare',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='economy_fare',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='first_fare',
            field=models.IntegerField(default=0),
        ),
    ]
